Detect Images Directory
hoetmaaiers/metalsmith-project-images pull request #5
Opened 2016-10-12 17:56 UTC by nianwang

Skip requiring a physical images directory in matching project patterns.

### Use Case

As noted in #4 , every matching project pattern requires a specified `imagesDirectory`.

When there are no images available, it's possible the directory will not exist. Especially in Git, empty folders are routinely removed from tracking. Instead of requiring the directory exist (or use a trick like `images/.placeholder`), we simply silently skip missing directories.

### Changelog

- Add check if the `imagesDirectory` exists and skip if needed
- Fix typo in test comment
- Remove debug console reference in test output

2016-10-13 10:52 UTC, hoetmaaiers commented on src/index.js
> +    try {
I dislike the try catch approach. Especially because nothing is being catched. A better apporach would be to check if the images path exists. If it doesn't exist, just return false and continue to the next loop iteration.

2016-10-13 10:55 UTC, hoetmaaiers requested changes
Thanks for your PR contribution! 2 remarks before the PR will be merged:
- please use a different approach then `try ... catch`
- add the optional presence of images directory to the README.md

2016-10-16 07:07 UTC, nianwang commented
For compatibility with earlier version of node (and iojs), switched to `fs.exists` instead of `fs.access`.

2016-10-16 15:17 UTC, hoetmaaiers approved these changes

2016-10-16 15:17 UTC, hoetmaaiers approved these changes
Thank you!

2016-10-16 15:17 UTC, merged